return {}
-- return {
--   {'akinsho/bufferline.nvim', 
--     version = "*",
--     dependencies = 'nvim-tree/nvim-web-devicons',
--     config = function()
--       require("bufferline").setup {
--         options = {
--           indicator_icon = nil,
--           indicator = { style = "icon", icon = "▎"},
--           buffer_close_icon = '',
--           modified_icon = "●",
--           close_icon = "",
--           left_trunc_marker = "",
--           right_trunc_marker = "",
--           max_name_length = 30,
--           tab_size = 21,
--           diagnostics_update_in_insert = false,
--           offsets = { { filetype = "NvimTree", text = "", padding = 1 } },
--           show_buffer_icons = true,
--           show_buffer_close_icons = true,
--           show_close_icon = true,
--           show_tab_indicators = true,
--           enforce_regular_tabs = true,
--           always_show_bufferline = true,
--         },
--         highlights = {
--           fill = {
--             fg = { attribute = "fg", highlight = "Visual" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--           background = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--
--           buffer_visible = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--
--           close_button = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--           close_button_visible = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--
--           tab_selected = {
--             fg = { attribute = "fg", highlight = "Normal" },
--             bg = { attribute = "bg", highlight = "Normal" },
--           },
--           tab = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--           tab_close = {
--             fg = { attribute = "fg", highlight = "TabLineSel" },
--             bg = { attribute = "bg", highlight = "Normal" },
--           },
--
--           duplicate_selected = {
--             fg = { attribute = "fg", highlight = "TabLineSel" },
--             bg = { attribute = "bg", highlight = "TabLineSel" },
--             underline = true,
--           },
--           duplicate_visible = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--             underline = true,
--           },
--           duplicate = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--             underline = true,
--           },
--
--           modified = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--           modified_selected = {
--             fg = { attribute = "fg", highlight = "Normal" },
--             bg = { attribute = "bg", highlight = "Normal" },
--           },
--           modified_visible = {
--             fg = { attribute = "fg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--
--           separator = {
--             fg = { attribute = "bg", highlight = "TabLine" },
--             bg = { attribute = "bg", highlight = "TabLine" },
--           },
--           separator_selected = {
--             fg = { attribute = "bg", highlight = "Normal" },
--             bg = { attribute = "bg", highlight = "Normal" },
--           },
--           indicator_selected = {
--             fg = { attribute = "fg", highlight = "LspDiagnosticsDefaultHint" },
--             bg = { attribute = "bg", highlight = "Normal" },
--           },
--         },
--       }
--       vim.keymap.set("n", "<leader>x", vim.cmd.bdelete, {desc = "Close current buffer"})
--       vim.keymap.set("n", "L", ":BufferLineCycleNext<CR>", { desc = "Go to next buffer" })
--       vim.keymap.set("n", "H", ":BufferLineCyclePrev<CR>", { desc = "Go to previous buffer" })
--
--     end
--   }
-- }
